# Recap for Numpy

## Numpy exercises

In [1]:
# 1. Import the numpy package as np
import numpy as np

In [2]:
# 2. Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]

In [3]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

In [6]:
# 4. Find the shape of the matrix from the previous exercise
print(matrix.shape)

(3, 3)

In [8]:
# 5. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [9]:
# 6. Create a 1D array of 10 random values between 0 and 1
random_arr = np.random.rand(10)
print(random_arr)

[0.22246571 0.56263274 0.47189961 0.74854614 0.41060569 0.00604011
 0.88152393 0.71478901 0.24709194 0.12110876]

In [10]:
# 7. Create an array of 25 random integers between 1 and 100, and reshape it to a 5x5 matrix
random_matrix = np.random.randint(1, 101, 25).reshape(5, 5)
print(random_matrix)

[[85 65 67 99 73]
 [66 90 87 93 80]
 [32 56 75  4 74]
 [99 20 83 65 28]
 [18 18 10  3  4]]

In [11]:
# 8. Find the sum of all the elements in the matrix from the previous exercise
print(random_matrix.sum())

1394

In [12]:
# 9. Find the mean, max, and min values of the 5x5 matrix from the previous exercise
print("Mean:", random_matrix.mean())
print("Max:", random_matrix.max())
print("Min:", random_matrix.min())

Mean: 55.76
Max: 99
Min: 3

In [13]:
# 10. Create a 1D array of 10 values, all set to 7
sevens = np.full(10, 7)
print(sevens)

[7 7 7 7 7 7 7 7 7 7]

In [14]:
# 11. Create a 1D array of 20 values, equally spaced between 0 and 1
linspace_arr = np.linspace(0, 1, 20)
print(linspace_arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

In [15]:
# 12. Extract all odd numbers from an array of integers from 0 to 19 (exact division by 2)
arr = np.arange(20)
odd_numbers = arr[arr % 2 == 1]
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19]

In [16]:
# 13. Replace all odd numbers in an array with -1
arr[arr % 2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]

In [17]:
# 14. Create two 2D arrays of size 3x3, filled with random numbers, and perform matrix addition
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
matrix_sum = matrix1 + matrix2
print(matrix_sum)

[[0.24079461 1.07081233 0.49186502]
 [0.93591627 0.47748952 0.38646244]
 [1.02775201 0.84440223 1.07834948]]

In [18]:
# 15. Multiply two 2D arrays element-wise (Hadamard Product)
matrix_product = matrix1 * matrix2
print(matrix_product)

[[0.01348369 0.22824192 0.06047736]
 [0.21769792 0.01669415 0.0030875 ]
 [0.22167454 0.15681076 0.26120391]]

In [19]:
# 16. Perform matrix multiplication (dot product) of two 3x3 matrices, example, (2*3)(3*2) = (2*2)
matrix_dot_product = np.dot(matrix1, matrix2)
print(matrix_dot_product)

[[0.3157273  0.38588604 0.322084  ]
 [0.06692025 0.41286455 0.14525566]
 [0.41088506 0.56945037 0.44198698]]

In [20]:
# 17. Create a 1D array of 10 random integers between 1 and 50, then sort the array
random_ints = np.random.randint(1, 51, 10)
print(random_ints)

[44  6 37 44 17 38 22 49 42 40]

In [21]:
sorted_ints = np.sort(random_ints)
print(sorted_ints)

[ 6 17 22 37 38 40 42 44 44 49]

In [22]:
# 18. Stack two 1D arrays vertically and horizontally
arr1 = np.random.randint(1, 10, 5)
arr2 = np.random.randint(1, 10, 5)
print("Vertical Stack:\n", np.vstack((arr1, arr2)))
print("Horizontal Stack:\n", np.hstack((arr1, arr2)))

Vertical Stack:
 [[2 5 6 8 2]
 [2 3 6 8 5]]
Horizontal Stack:
 [2 5 6 8 2 2 3 6 8 5]

In [23]:
# 19. Create a 4x4 matrix and extract the diagonal elements
matrix_4x4 = np.random.randint(1, 101, 16).reshape(4, 4)
diagonal = np.diag(matrix_4x4)
print("Matrix:\n", matrix_4x4)
print("Diagonal:", diagonal)

Matrix:
 [[42 27 78 52]
 [62 95  4  3]
 [44  7 94  6]
 [25 64 17 99]]
Diagonal: [42 95 94 99]

In [27]:
# 20. Create a 5x5 matrix of random integers between 1 and 100, and replace all even numbers with 0
matrix_5x5 = np.random.randint(1, 101, 25).reshape(5, 5)
print(matrix_5x5)

[[ 56  86  96  83  22]
 [ 50  24   2  55   3]
 [ 81  68  47 100   8]
 [ 79  22  52  75  25]
 [ 98  55  33  65  21]]

In [28]:
matrix_5x5[matrix_5x5 % 2 == 0] = 0
print(matrix_5x5)

[[ 0  0  0 83  0]
 [ 0  0  0 55  3]
 [81  0 47  0  0]
 [79  0  0 75 25]
 [ 0 55 33 65 21]]

## Optional exercises

In [64]:
# 21. Create a 5x5 matrix with values 1 to 25, extract the 3x3 submatrix from the center
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
submatrix_3x3 = matrix_5x5[1:4, 1:4]  # extract the center 3x3 submatrix
print("Original 5x5 Matrix:\n", matrix_5x5)
print("3x3 Submatrix from the center:\n", submatrix_3x3)

Original 5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
3x3 Submatrix from the center:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

In [68]:
# 22. Create a 6x6 matrix and set the border elements (first and last rows and columns) to -1
matrix_6x6 = np.random.randint(1, 101, 36).reshape(6, 6)
print("6x6 Matrix:\n", matrix_6x6)
matrix_6x6[[0, -1], :] = -1  # set the first and the last row to -1
print("matrix_6x6 with first and the last row to -1", matrix_6x6)
matrix_6x6[:, [0, -1]] = -1  # set the first and the last column to -1
print("6x6 Matrix with border elements set to -1:\n", matrix_6x6)

6x6 Matrix:
 [[66 53 99 91 55 56]
 [45 85 69 48 76  6]
 [ 6 35  8 73 90 77]
 [48 51 64 41 94 23]
 [81 23 75 78 34 89]
 [79 66 20 47 93 54]]
matrix_6x6 with first and the last row to -1 [[-1 -1 -1 -1 -1 -1]
 [45 85 69 48 76  6]
 [ 6 35  8 73 90 77]
 [48 51 64 41 94 23]
 [81 23 75 78 34 89]
 [-1 -1 -1 -1 -1 -1]]
6x6 Matrix with border elements set to -1:
 [[-1 -1 -1 -1 -1 -1]
 [-1 85 69 48 76 -1]
 [-1 35  8 73 90 -1]
 [-1 51 64 41 94 -1]
 [-1 23 75 78 34 -1]
 [-1 -1 -1 -1 -1 -1]]

In [80]:
# 23. Create a 7x7 matrix and reverse the rows and columns
matrix_7x7 = np.random.randint(1, 101, 49).reshape(7, 7)
print("Original 7x7 Matrix:\n", matrix_7x7)
print("----------------------------------")
# solution 1, reverse sequentially
reversed_row = matrix_7x7[::-1, :]  # reverse the rows
print("Reversed rows of 7x7 Matrix:\n", reversed_row)
print("----------------------------------")
reversed_columns = reversed_row[:, ::-1]  # reverse the columns
print("Reversed columns of 7x7 Matrix:\n", reversed_columns)
print("----------------------------------")

#solution 2, reverse simultaneously
reversed_matrix = matrix_7x7[::-1, ::-1]  # reverse the rows and columns

print("Reversed 7x7 Matrix:\n", reversed_matrix)

Original 7x7 Matrix:
 [[ 19  89   1  95  87  76  46]
 [ 90  18  71  99  36  71  51]
 [ 38  48  19  98  60   8  84]
 [ 48  43  80  19   1  25  14]
 [ 57  82  52  38  62  37  94]
 [ 69   4  55  78  19  80  38]
 [ 82  23 100  57  43  36  68]]
----------------------------------
Reversed rows of 7x7 Matrix:
 [[ 82  23 100  57  43  36  68]
 [ 69   4  55  78  19  80  38]
 [ 57  82  52  38  62  37  94]
 [ 48  43  80  19   1  25  14]
 [ 38  48  19  98  60   8  84]
 [ 90  18  71  99  36  71  51]
 [ 19  89   1  95  87  76  46]]
----------------------------------
Reversed columns of 7x7 Matrix:
 [[ 68  36  43  57 100  23  82]
 [ 38  80  19  78  55   4  69]
 [ 94  37  62  38  52  82  57]
 [ 14  25   1  19  80  43  48]
 [ 84   8  60  98  19  48  38]
 [ 51  71  36  99  71  18  90]
 [ 46  76  87  95   1  89  19]]
----------------------------------
Reversed 7x7 Matrix:
 [[ 68  36  43  57 100  23  82]
 [ 38  80  19  78  55   4  69]
 [ 94  37  62  38  52  82  57]
 [ 14  25   1  19  80  43  48]
 [ 84   8  60  98  19  48  38]
 [ 51  71  36  99  71  18  90]
 [ 46  76  87  95   1  89  19]]

In [81]:
# 24. Create a 1D array of 10 integers and replace the elements at indices 2, 5, and 7 with 99 using advanced indexing
arr_1d = np.arange(10)
arr_1d[[2, 5, 7]] = 99  # using advanced indexing replace the elements at indices
print("Array after replacing elements at indices 2, 5, and 7:\n", arr_1d)

Array after replacing elements at indices 2, 5, and 7:
 [ 0  1 99  3  4 99  6 99  8  9]

In [83]:
# 25. Create a 5x5 matrix and swap the first and last rows
matrix_5x5_swap = np.random.randint(1, 101, 25).reshape(5, 5)
print("5x5 Matrix before swapping first and last rows:\n", matrix_5x5_swap)
print("----------------------------------")
matrix_5x5_swap[[0, -1]] = matrix_5x5_swap[[-1, 0]]  # swap the first and last rows
print("5x5 Matrix after swapping first and last rows:\n", matrix_5x5_swap)

5x5 Matrix before swapping first and last rows:
 [[15 81 83 31 79]
 [96 75 65 59 69]
 [ 6  6 10 83 22]
 [57  1 74 72 35]
 [ 3 50 60 31 98]]
----------------------------------
5x5 Matrix after swapping first and last rows:
 [[ 3 50 60 31 98]
 [96 75 65 59 69]
 [ 6  6 10 83 22]
 [57  1 74 72 35]
 [15 81 83 31 79]]

# Tutorial 5: Pandas Data Structures: Series and DataFrames
TA: ZHANG Wei

E-mail: wzhang472-c@my.cityu.edu.hk

### Introduction
Pandas is an open source library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language.


Series is a one-dimensional labeled array capable of holding any data type like integers, strings, floating point numbers, Python objects, etc.


DataFrames is a data structure that organizes data into a two-dimensional table of rows and columns.

### Install
Use the command "pip install pandas" in your terminal to install pandas


### What you can learn on this tutorial
1.How to create series

2.How to check the index of series

3.How to compute the statistical information(mean,sum, etc.) of series

4.How to select information you want in series

5.How to creat DataFrames

6.Basic operations about DataFrames

### Background

Where to eat? It is a question.

Given information about the average spending(HKD), ratings(Ten-points system), walk time from library(Lib, minute) and dormitory (Dor, minute) of (part of) canteens  around CityU in the following table:


| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |  

FYI, catering at CityU: https://www.cityu.edu.hk/zh-hk/directories/catering

In [29]:
# Hint: You may need to import the related packages first
import pandas as pd

### Questions about Series

#### Question 1:
Create series for Price, Rating, Lib, Dor separately using at least two different ways. Write you code and print your results.

Hints 1:{"AC1":3, "AC2":8, "AC3":8, "Mcdonald":5, "Subway":6.5, "Taste":7, "FestivalFood":7, "HomeyKitchen":16, "ChineseRestaurant":7, "KebabStation":3}

Hints 2: ["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"]

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [30]:
# price
price = (32,42,55,45,44,50,65,35,90,45)
index=["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"]
price_series = pd.Series(price,index)
price_series

AC1                  32
AC2                  42
AC3                  55
Mcdonald             45
Subway               44
Taste                50
FestivalFood         65
HomeyKitchen         35
ChineseRestaurant    90
KebabStation         45
dtype: int64

In [31]:
# Rating 
rating = (5,7,8,7.5,6,8,9,4,9,7.5)
rating_series = pd.Series(rating)
print("before adding index\n",rating_series)
rating_series.index = ["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"]
print("----------------------------\nafter adding index\n",rating_series)

before adding index
 0    5.0
1    7.0
2    8.0
3    7.5
4    6.0
5    8.0
6    9.0
7    4.0
8    9.0
9    7.5
dtype: float64
----------------------------
after adding index
 AC1                  5.0
AC2                  7.0
AC3                  8.0
Mcdonald             7.5
Subway               6.0
Taste                8.0
FestivalFood         9.0
HomeyKitchen         4.0
ChineseRestaurant    9.0
KebabStation         7.5
dtype: float64

In [32]:
# Dor
Dor_series = pd.Series((13,9,6,18,10,20,20,5,15,13), index=["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"])
Dor_series

AC1                  13
AC2                   9
AC3                   6
Mcdonald             18
Subway               10
Taste                20
FestivalFood         20
HomeyKitchen          5
ChineseRestaurant    15
KebabStation         13
dtype: int64

In [33]:
# Lib
Lib = {"AC1":3, "AC2":8, "AC3":8, "Mcdonald":5, "Subway":6.5, "Taste":7, "FestivalFood":7, "HomeyKitchen":16, "ChineseRestaurant":7, "KebabStation":3}
Lib_series = pd.Series(Lib)
Lib_series

AC1                   3.0
AC2                   8.0
AC3                   8.0
Mcdonald              5.0
Subway                6.5
Taste                 7.0
FestivalFood          7.0
HomeyKitchen         16.0
ChineseRestaurant     7.0
KebabStation          3.0
dtype: float64

#### Question 2
2.1 Suppose you want to query the average price of AC1, based on the series you created, write the code using explicit index 'AC1' and output your results.

2.2 Suppose you want to query the walking time from the dormitory to AC3, based on the series you created, write the code using integer index and output your results.

2.3 Suppose you want to visit all the canteens around CityU from library, based on the series you created, write the code and output the total time you need.

Hint 1: the interger index is started from 0

Hint 2: you may need  to use the function sum() to take the sum of series

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [34]:
# 2.1
price_series['AC1']

32

In [35]:
# 2.2
Dor_series[2]

6

In [36]:
# 2.3
Lib_series.sum()

70.5

#### Question 3
3.1 Your parent asks you how much it costs to eat at CityU. To make it simple, you are going to tell them the average price of the school canteens. Based on the series you created, write the code and output the average price of canteens.

3.2 If the time from Li building to each canteen is half the time from the dormitory and the library to each canteen, what is the walking time from Li building to each canteen? Based on the series you created, write the code and output the result.

3.3 Suppose you want to go to the nearest canteen from the Li building, which canteens can you choose? Based on the series you created, write the code and output the result.

Hint 1: you may need to use mean() to take the mean value of series

Hint 2: you may need to use add() or "+"

Hint 3: you may need to use idxmin(), return index label of the minimum values.

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [37]:
#3.1
price_series.mean()

50.3

In [38]:
#3.2
(Dor_series+Lib_series)/2

AC1                   8.00
AC2                   8.50
AC3                   7.00
Mcdonald             11.50
Subway                8.25
Taste                13.50
FestivalFood         13.50
HomeyKitchen         10.50
ChineseRestaurant    11.00
KebabStation          8.00
dtype: float64

In [40]:
#3.2
Li_series = Dor_series
Li_series = Li_series.add(Lib_series)/2
Li_series

AC1                   8.00
AC2                   8.50
AC3                   7.00
Mcdonald             11.50
Subway                8.25
Taste                13.50
FestivalFood         13.50
HomeyKitchen         10.50
ChineseRestaurant    11.00
KebabStation          8.00
dtype: float64

In [41]:
# 3.3
Li_series.idxmin()

'AC3'

#### Question 4
4.1 If your budget for lunch is 55 hkd, but you want to eat the highest rated canteens, how many options do you have? Based on the series you created, write the code and print the result.

Hint 1: for question 4.1 you need to select the canteens with price <=  55 first, and get their index, then use the index to find the highest rating in the rating series you have built, finally count the number of canteens.

Hint 2: you may need to use max() to take the maximum value of a series

Hint 3: you may need to use len() to take the length of a series

-- -- -- 

4.2 Suppose you are studying in the dormitory today, and your budget for lunch is 50 hkd. In order to set aside more time for study, you want to find the nearest canteens. Where do you decide to eat for the lunch? Based on the series you created, write the code and print the result.

Hint 4: you may need to find a canteen which has price lower than 50, and then choose the nearest one.

Hint 5: you may need to use idxmin() to find the label of the minimum value of series

-- -- --

4.3 (This subquestion is not required) If you plan to eat lunch and dinner near CityU today, and the budget is 82 hkd, you want to eat the canteens with the highest sum of ratings today, where do you decide to eat? Based on the series you created, write the code and print the result.

Hint 6: you may need to use two loops to traverse the price_series

Hint 7: you may need to use if arguement to select the canteens which price sum is lower than 82.

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [42]:
# 4.1
sub_price = price_series[price_series <= 55]  # find the canteens with price <=  55
price_index = sub_price.index                 # index of the sub_price

highest_rating = rating_series[price_index].max()                       # find the highest rating
number_of_options = len(rating_series[rating_series == highest_rating]) # compute the number of options
number_of_options

2

In [44]:
# 4.2 
less_than_50_canteens = price_series[price_series <= 50]# select canteens prices <= 50
less_than_50_index = less_than_50_canteens.index        # take the index of canteens
Dor_series[less_than_50_index].idxmin()                 # choose the label of the minimum value of the Dor_series

'HomeyKitchen'

In [45]:
# 4.2
Dor_series[price_series <= 50].idxmin()

'HomeyKitchen'

In [46]:
# 4.3
rating_max = 0            #initialize the maximum rating sum
canteen_lunch = []        #initialize the lunch place
canteen_dinner = []       #initialize the dinner place
for lunch in price_series.index:       # loop for lunch
    for dinner in price_series.index:  # loop for dinner
        if(price_series[lunch]+price_series[dinner]<=82): # choose two canteens whose price sum is lower than 82
            if(rating_series[lunch]+rating_series[dinner]>=rating_max): 
                rating_max = rating_series[lunch]+rating_series[dinner] # update the maximum rating sum
                canteen_lunch = lunch                                   # update the lunch place
                canteen_dinner = dinner                                 # update the dinner place

print(canteen_lunch)  #print your result
print(canteen_dinner)

Taste
AC1

In [47]:
price_series.index

Index(['AC1', 'AC2', 'AC3', 'Mcdonald', 'Subway', 'Taste', 'FestivalFood',
       'HomeyKitchen', 'ChineseRestaurant', 'KebabStation'],
      dtype='object')

In [48]:
for lunch in price_series.index: 
    print(lunch)

AC1
AC2
AC3
Mcdonald
Subway
Taste
FestivalFood
HomeyKitchen
ChineseRestaurant
KebabStation

### Questions about DataFrames

In [49]:
# you may need to use the following information first
import pandas as pd 
# create series
price_series = pd.Series((32,42,55,45,44,50,65,35,90,45),["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"])
rating_series = pd.Series((5,7,8,7.5,6,8,9,4,9,7.5),["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"])
Dor_series = pd.Series((13,9,6,18,10,20,20,5,15,13), index=["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"])
Lib_series = pd.Series({"AC1":3, "AC2":8, "AC3":8, "Mcdonald":5, "Subway":6.5, "Taste":7, "FestivalFood":7, "HomeyKitchen":16, "ChineseRestaurant":7, "KebabStation":3})

#### Question 5
Create Dataframe structure using at least two different ways and print your dataframe

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [51]:
# use series create dataframe
CityU_Canteens = pd.DataFrame({'price':price_series,'rating':rating_series,'Dor': Dor_series,'Lib':Lib_series})
CityU_Canteens

                   price  rating  Dor   Lib
AC1                   32     5.0   13   3.0
AC2                   42     7.0    9   8.0
AC3                   55     8.0    6   8.0
Mcdonald              45     7.5   18   5.0
Subway                44     6.0   10   6.5
Taste                 50     8.0   20   7.0
FestivalFood          65     9.0   20   7.0
HomeyKitchen          35     4.0    5  16.0
ChineseRestaurant     90     9.0   15   7.0
KebabStation          45     7.5   13   3.0

In [52]:
CityU_Canteens = pd.DataFrame(
    {   "price": (32,42,55,45,44,50,65,35,90,45),
        "rating": (5,7,8,7.5,6,8,9,4,9,7.5),
        "Dor": (13,9,6,18,10,20,20,5,15,13),
        "Lib": (3,8,9,5,6.5,7,7,16,7,3),
    })
CityU_Canteens.index=["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"]
CityU_Canteens

                   price  rating  Dor   Lib
AC1                   32     5.0   13   3.0
AC2                   42     7.0    9   8.0
AC3                   55     8.0    6   9.0
Mcdonald              45     7.5   18   5.0
Subway                44     6.0   10   6.5
Taste                 50     8.0   20   7.0
FestivalFood          65     9.0   20   7.0
HomeyKitchen          35     4.0    5  16.0
ChineseRestaurant     90     9.0   15   7.0
KebabStation          45     7.5   13   3.0

In [53]:
CityU_Canteens  = pd.DataFrame({'price':(32,42,55,45,44,50,65,35,90,45)})
CityU_Canteens['rating'] = [5,7,8,7.5,6,8,9,4,9,7.5]
CityU_Canteens['Dor'] = [13,9,6,18,10,20,20,5,15,13]
CityU_Canteens['Lib'] = [3,8,9,5,6.5,7,7,16,7,3]
CityU_Canteens.index = ["AC1", "AC2", "AC3", "Mcdonald", "Subway", "Taste", "FestivalFood", "HomeyKitchen", "ChineseRestaurant", "KebabStation"]

CityU_Canteens

                   price  rating  Dor   Lib
AC1                   32     5.0   13   3.0
AC2                   42     7.0    9   8.0
AC3                   55     8.0    6   9.0
Mcdonald              45     7.5   18   5.0
Subway                44     6.0   10   6.5
Taste                 50     8.0   20   7.0
FestivalFood          65     9.0   20   7.0
HomeyKitchen          35     4.0    5  16.0
ChineseRestaurant     90     9.0   15   7.0
KebabStation          45     7.5   13   3.0

#### Question 6
6.1 select the first 5 rows in at least two ways based on the dataframe you created,write the code and print your results

6.2 Select the price and rating columns in at least two ways based on the dataframe you created, write the code and print your results

6.3 What canteens from the library with walking time < 10 and rating >7? Based on the dataframe you created, write the code and print the result.

Hint 1: head()

Hint 2: iloc[]

Hint 3: loc[]

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [54]:
# 6.1
CityU_Canteens.head(5)
CityU_Canteens.iloc[:5]            # implicitly uses the index, only integer
CityU_Canteens.loc['AC1':'Subway'] # explicitly uses the index

          price  rating  Dor  Lib
AC1          32     5.0   13  3.0
AC2          42     7.0    9  8.0
AC3          55     8.0    6  9.0
Mcdonald     45     7.5   18  5.0
Subway       44     6.0   10  6.5

In [55]:
# 6.2 
CityU_Canteens.iloc[:,[0, 1]]             # implicitly uses the index
CityU_Canteens.loc[:,["price", "rating"]] # explicitly uses the index
CityU_Canteens[['price', 'rating']]       # dict

                   price  rating
AC1                   32     5.0
AC2                   42     7.0
AC3                   55     8.0
Mcdonald              45     7.5
Subway                44     6.0
Taste                 50     8.0
FestivalFood          65     9.0
HomeyKitchen          35     4.0
ChineseRestaurant     90     9.0
KebabStation          45     7.5

In [56]:
# 6.3 
CityU_Canteens[(CityU_Canteens['Lib']<10) & (CityU_Canteens["rating"]>7)]

                   price  rating  Dor  Lib
AC3                   55     8.0    6  9.0
Mcdonald              45     7.5   18  5.0
Taste                 50     8.0   20  7.0
FestivalFood          65     9.0   20  7.0
ChineseRestaurant     90     9.0   15  7.0
KebabStation          45     7.5   13  3.0

#### Question 7
You just woke up today, and you feel that it is too troublesome to consider where to eat based on price, walking time, and rating, so you decide to combine these three indicators to calculate your own indicator, and decide where to eat breakfast based on this indicator. 

7.1 Please compute your indicator based on this equation: score = Rating×0.5-Price×0.02 -Dor×0.05. Based on the dataframe you created, add a column name "score"  and print the canteens you want to go based on the maximum value of this score.

7.2 You think your score is too subjective, so you want to delete this column in case someone else know your preference(you are a privacy-conscious person).Based on the dataframe you created, delete the column "score" and print new dataframe.

Hint 1: you may need to use function insert() to add a new column

Hint 2: you may need to use function  max() to compute the max value of one column

Hint 3: you may need to use function drop() to delete a column

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [57]:
# 7.1 
score = CityU_Canteens["rating"]*0.5-CityU_Canteens["price"]*0.02-CityU_Canteens["Dor"]*0.05 # compute the score
CityU_Canteens.insert(4,"score",score)                     # insert the score column
max_score = CityU_Canteens["score"].max()                  # take the max value of the score
CityU_Canteens[CityU_Canteens["score"]==max_score].index   # find the Canteen with the max score

Index(['AC3'], dtype='object')

In [58]:
CityU_Canteens

                   price  rating  Dor   Lib  score
AC1                   32     5.0   13   3.0   1.21
AC2                   42     7.0    9   8.0   2.21
AC3                   55     8.0    6   9.0   2.60
Mcdonald              45     7.5   18   5.0   1.95
Subway                44     6.0   10   6.5   1.62
Taste                 50     8.0   20   7.0   2.00
FestivalFood          65     9.0   20   7.0   2.20
HomeyKitchen          35     4.0    5  16.0   1.05
ChineseRestaurant     90     9.0   15   7.0   1.95
KebabStation          45     7.5   13   3.0   2.20

In [59]:
# 7.2
print("before deleting score\n",CityU_Canteens)
CityU_Canteens = CityU_Canteens.drop("score", axis=1)
print("\n---------------------------\nafter deleting score\n",CityU_Canteens)

before deleting score
                    price  rating  Dor   Lib  score
AC1                   32     5.0   13   3.0   1.21
AC2                   42     7.0    9   8.0   2.21
AC3                   55     8.0    6   9.0   2.60
Mcdonald              45     7.5   18   5.0   1.95
Subway                44     6.0   10   6.5   1.62
Taste                 50     8.0   20   7.0   2.00
FestivalFood          65     9.0   20   7.0   2.20
HomeyKitchen          35     4.0    5  16.0   1.05
ChineseRestaurant     90     9.0   15   7.0   1.95
KebabStation          45     7.5   13   3.0   2.20

---------------------------
after deleting score
                    price  rating  Dor   Lib
AC1                   32     5.0   13   3.0
AC2                   42     7.0    9   8.0
AC3                   55     8.0    6   9.0
Mcdonald              45     7.5   18   5.0
Subway                44     6.0   10   6.5
Taste                 50     8.0   20   7.0
FestivalFood          65     9.0   20   7.0
HomeyKitchen          35     4.0    5  16.0
ChineseRestaurant     90     9.0   15   7.0
KebabStation          45     7.5   13   3.0

#### Question 8

There are activities in CityU canteens today. Show your student card in the canteens and you can get a meal coupon for this canteen, and you can consume any set meal. Sadly, these activities take place at the same time and you can only go to one canteen. Which canteens do you want to go ?(considering the rating first and then considering the price). Based on the dataframe you created, write your code and print your results.

Hint 1: you may need to use the function sort_values() to sort the dataframe

| Canteens    | Price  | Rating  | Lib  | Dor| 
|-----------------|--------|-------- |------|----|
| AC1         | 32    | 5     | 3   | 13 |
| AC2         | 42    | 7     | 8   | 9  |
| AC3         | 55    | 8     | 8   | 6  | 
| Mcdonald      | 45    | 7.5    | 5   | 18 | 
| Subway       | 44    | 6     | 6.5  | 10 | 
| Taste        | 50    | 8     | 7   | 20 | 
| FestivalFood   | 65    | 9     | 7   | 20 | 
| HomeyKitchen   | 35    | 4     |16   | 5  | 
|ChineseRestaurant| 90    | 9     | 7   | 15 |
|KebabStation    | 45    | 7.5    | 3   | 13 |

In [60]:
sorted_rating = CityU_Canteens.sort_values(by="rating",ascending=False) #sort the rating list by descending order
sorted_rating

                   price  rating  Dor   Lib
FestivalFood          65     9.0   20   7.0
ChineseRestaurant     90     9.0   15   7.0
AC3                   55     8.0    6   9.0
Taste                 50     8.0   20   7.0
Mcdonald              45     7.5   18   5.0
KebabStation          45     7.5   13   3.0
AC2                   42     7.0    9   8.0
Subway                44     6.0   10   6.5
AC1                   32     5.0   13   3.0
HomeyKitchen          35     4.0    5  16.0

In [61]:
sorted_price = sorted_rating.sort_values(by="price",ascending=False)#sort the price list by descending order
sorted_price

                   price  rating  Dor   Lib
ChineseRestaurant     90     9.0   15   7.0
FestivalFood          65     9.0   20   7.0
AC3                   55     8.0    6   9.0
Taste                 50     8.0   20   7.0
Mcdonald              45     7.5   18   5.0
KebabStation          45     7.5   13   3.0
Subway                44     6.0   10   6.5
AC2                   42     7.0    9   8.0
HomeyKitchen          35     4.0    5  16.0
AC1                   32     5.0   13   3.0

In [62]:
sorted_price.index[0] #print the canteen you want to go

'ChineseRestaurant'